### PR TITLE
update iOS order and links

### PR DESCRIPTION
**Pull request by kevjaro**
addressing issues mentioned in #25

+ checked all links and their validity
+ removed uselessly mentioned information ("iOS", "open-source" since repo is linked anyway)
+ commented out Mona (not yet released)
+ commented out Mastoon (no valid links available)

### CODE REVIEW

**Comment by hueyy** [comment]
This is fantastic

**Comment by kevjaro** [comment]
> This is fantastic

Thanks! :)

**Comment by hueyy** [comment]
@all-contributors please add @Nive9 for maintenance

**Comment by hueyy** [comment]
https://github.com/all-contributors?type=source please add @Nive9 for maintenance

**Comment by hueyy** [comment]
@all-contributors please add @Nive9 for maintenance

**Pull request merged**
